import { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { RefreshCw, Code, MessageSquare, Bell, Activity } from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Persona } from '@/lib/types';
import { CodeGenerationMonitor } from '@/components/CodeGenerationMonitor';
import { ChatTab } from '@/components/ChatTab';

interface LogEntry {
  id: string;
  message: string;
  timestamp: Date;
  type: 'debug' | 'info' | 'warning' | 'error' | 'success';
  canRollback: boolean;
}

interface PerformanceTabProps {
  persona?: Persona;
  projectId: number;
}

export function PerformanceTab({ persona, projectId }: PerformanceTabProps) {
  const [activeTab, setActiveTab] = useState<string>('code');
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [lastUpdated, setLastUpdated] = useState<Date>(new Date());
  
  // Initialize logs from API or websocket data source
  useEffect(() => {
    // This hook will be used to load actual log data from the backend API
    // or subscribe to real-time log updates via WebSocket
    
    // TODO: Replace with actual API call or WebSocket subscription
    
    // Example implementation (commented out):
    // const fetchLogs = async () => {
    //   try {
    //     const response = await fetch(`/api/personas/${persona.id}/logs`);
    //     const data = await response.json();
    //     setLogs(data);
    //   } catch (error) {
    //     console.error('Error fetching logs:', error);
    //   }
    // };
    // fetchLogs();
    
    // Or with WebSocket:
    // const handleLogUpdate = (data) => {
    //   if (data.personaId === persona.id) {
    //     setLogs(prev => [...prev, data.log]);
    //   }
    // };
    // socket.on('log_update', handleLogUpdate);
    // return () => socket.off('log_update', handleLogUpdate);
  }, []);
  
  // Format time for display
  const formatTime = (date: Date) => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  };
  
  // Handle log rollback
  const handleRollback = (logId: string) => {
    // TODO: Implement actual API call to perform rollback
    console.log('Rolling back action:', logId);
    
    // Example API call (commented out):
    // const performRollback = async (id: string) => {
    //   try {
    //     const response = await fetch(`/api/logs/${id}/rollback`, {
    //       method: 'POST',
    //     });
    //     const result = await response.json();
    //     
    //     if (result.success) {
    //       // Update local logs or trigger refresh
    //     }
    //   } catch (error) {
    //     console.error('Rollback failed:', error);
    //   }
    // };
    // performRollback(logId);
  };
  
  // Refresh logs
  const refreshLogs = () => {
    setIsProcessing(true);
    
    // TODO: Implement actual API call to fetch latest logs
    
    // Example implementation (commented out):
    // const fetchLatestLogs = async () => {
    //   try {
    //     const response = await fetch(`/api/personas/${persona.id}/logs?fresh=true`);
    //     const data = await response.json();
    //     setLogs(data);
    //   } catch (error) {
    //     console.error('Error refreshing logs:', error);
    //   } finally {
    //     setLastUpdated(new Date());
    //     setIsProcessing(false);
    //   }
    // };
    // fetchLatestLogs();
    
    // Temporary placeholder:
    setLastUpdated(new Date());
    setIsProcessing(false);
  };
  
  return (
    <div className="grid grid-cols-2 gap-4 h-full">
      <div className="space-y-4">
        {/* Live Code Display Area */}
        <Tabs defaultValue="code" className="w-full" onValueChange={setActiveTab}>
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="code" className="flex items-center">
              <Code className="w-4 h-4 mr-2" />
              <span>Live Code</span>
            </TabsTrigger>
            <TabsTrigger value="chat" className="flex items-center">
              <MessageSquare className="w-4 h-4 mr-2" />
              <span>Replit Chat</span>
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="code">
            <Card className="h-[calc(100vh-220px)]">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg flex justify-between items-center">
                  <span>Live Code Generation</span>
                </CardTitle>
                <CardDescription>
                  Real-time code being generated by GPT-4o
                </CardDescription>
              </CardHeader>
              <CardContent className="h-[calc(100vh-300px)]">
                {/* This is where the CodeGenerationMonitor will go */}
                <CodeGenerationMonitor 
                  projectId={projectId} 
                  personaId={persona ? Number(persona.id) : 0} 
                />
              </CardContent>
            </Card>
          </TabsContent>
          
          <TabsContent value="chat">
            <Card className="h-[calc(100vh-220px)]">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg">Replit-Style Chat</CardTitle>
                <CardDescription>
                  Chat with the system for custom operations
                </CardDescription>
              </CardHeader>
              <CardContent className="h-[calc(100vh-300px)]">
                {/* This is where the chat UI will go */}
                {persona && persona.id && <ChatTab personaId={persona.id.toString()} />}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
      
      <div className="space-y-4">
        {/* System Logs with Rollback */}
        <Card className="h-[calc(50vh-120px)]">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex justify-between items-center">
              <div className="flex items-center">
                <Bell className="w-5 h-5 mr-2" />
                <span>System Logs</span>
              </div>
              <Button 
                variant="outline" 
                size="sm" 
                onClick={refreshLogs}
                disabled={isProcessing}
              >
                {isProcessing ? (
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <RefreshCw className="w-4 h-4 mr-2" />
                )}
                Refresh
              </Button>
            </CardTitle>
            <CardDescription className="flex justify-between">
              <span>System events with rollback capability</span>
              <span className="text-xs text-gray-500">Last updated: {formatTime(lastUpdated)}</span>
            </CardDescription>
          </CardHeader>
          <CardContent className="h-[calc(50vh-200px)] p-0">
            <ScrollArea className="h-full rounded-md p-4">
              <div className="space-y-2 px-4">
                {logs.map((log) => (
                  <div 
                    key={log.id} 
                    className={`flex justify-between items-start p-2 rounded text-sm ${
                      log.type === 'error' ? 'bg-red-950/30 text-red-400' : 
                      log.type === 'warning' ? 'bg-yellow-950/30 text-yellow-400' : 
                      log.type === 'success' ? 'bg-green-950/30 text-green-400' : 
                      'bg-gray-800/50 text-gray-300'
                    }`}
                  >
                    <div className="flex-1">
                      <div className="flex items-center">
                        <span className="mr-2 text-xs text-gray-500">[{formatTime(log.timestamp)}]</span>
                        <span>{log.message}</span>
                      </div>
                    </div>
                    {log.canRollback && (
                      <Button 
                        variant="outline" 
                        size="sm" 
                        className="ml-2 h-6 px-2 py-0 text-xs hover:bg-red-900/30 hover:text-red-400"
                        onClick={() => handleRollback(log.id)}
                      >
                        Rollback
                      </Button>
                    )}
                  </div>
                ))}
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
        
        {/* Real-time Process Logs */}
        <Card className="h-[calc(50vh-120px)]">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center">
              <Activity className="w-5 h-5 mr-2" />
              <span>Real-time Process Logs</span>
            </CardTitle>
            <CardDescription>
              Detailed processing information for debugging
            </CardDescription>
          </CardHeader>
          <CardContent className="h-[calc(50vh-200px)]">
            {/* Process logs will be populated from WebSocket events */}
            <ScrollArea className="h-full bg-gray-900 rounded-md p-4">
              <div className="space-y-2">
                {/* Process logs will be rendered here through a WebSocket connection */}
                {/* Example structure (commented out for reference):
                <div className="text-sm p-2 rounded bg-gray-800/50 text-gray-300">
                  <div className="flex justify-between items-start">
                    <span className="whitespace-pre-wrap">[Message content]</span>
                    <span className="text-xs text-gray-500 ml-2 whitespace-nowrap">
                      [Timestamp]
                    </span>
                  </div>
                </div>
                */}
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}