name: Vercel Client CI

on:
  push:
    branches: [ main ]
    paths:
      - 'vercel/client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'vercel/client/**'

jobs:
  build-vercel-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vercel/client

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './vercel/client/package.json'

    - name: Install dependencies
      run: npm install

    - name: Verify build environment
      run: npm run verify
      
    - name: Build Vercel client
      run: npm run build